version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
    networks:
      - sd-net

networks:
  sd-net:
    external: true
